-- 게시글 등록
INSERT INTO BOARD( BRD_NO, BRD_TYPE, BRD_DIVIDE, BRD_ID, BRD_TITLE, BRD_CONTENT, BRD_GNO, BRD_STEP, BRD_INDENT, BRD_COUNT, BRD_AVAILABLE, BRD_DATE )
VALUES(1, 'COMMUNITY', 3, 'TEST1', '안녕하세요', 'ㅎㅎㅎㅎㅎ', 1, 0, 0, 0, 1, NOW() );

-- 답글 등록
INSERT INTO BOARD( BRD_NO, BRD_TYPE, BRD_DIVIDE, BRD_ID, BRD_TITLE, BRD_CONTENT, BRD_GNO, BRD_STEP, BRD_INDENT, BRD_COUNT, BRD_AVAILABLE, BRD_DATE )
VALUES( ( SELECT * FROM ( SELECT MAX(BRD_NO)+1 FROM BOARD ) A ),
                'COMMUNITY', 3, 'TEST1', '안녕하세요', 'ㅎㅎㅎㅎㅎ',
                ( SELECT * FROM ( SELECT BRD_GNO FROM BOARD WHERE BRD_NO = 1 ) X ),
                ( SELECT * FROM ( select brd_step+1 from board where brd_no=1002) X ),
                ( SELECT * FROM ( select brd_indent+1 from board where brd_no=1002) X ),
                0, 1, NOW() );

-- 답글로 먼저 등록된 게시글 STEP 증가
UPDATE BOARD SET BRD_STEP = BRD_STEP+1
WHERE
BRD_GNO = ( SELECT * FROM ( SELECT BRD_GNO FROM BOARD WHERE BRD_NO = 1 ) AS A )
AND
BRD_STEP > ( SELECT * FROM ( SELECT BRD_STEP FROM BOARD WHERE BRD_NO = 1 ) AS B );

-- 가장 높은 게시글 번호 조회
 SELECT MAX(BRD_NO) FROM BOARD;

-- 데이터로그 등록
INSERT INTO DATALOG(DLG_NO, DLG_FNO, DLG_TYPE, DLG_ID, DLG_TEXT, DLG_DATE)
VALUES(1, 1, 'community', 'test1', '안녕하세요ㅎㅎㅎ', NOW())

-- 해당 메뉴 리스트 조회
SELECT BRD_NO, BRD_TYPE, BRD_DIVIDE, BRD_ID, BRD_TITLE, BRD_CONTENT, BRD_GNO, BRD_STEP, BRD_INDENT, BRD_COUNT, BRD_AVAILABLE, BRD_DATE,
                          MEMBER.MBR_PROFILE, MEMBER.MBR_NICK,
                          COALESCE(BRD_LIKECOUNT,0) AS BRD_LIKECOUNT
FROM (
              SELECT * FROM BOARD
              WHERE BRD_TYPE = 'community'
              ORDER BY BRD_GNO DESC, BRD_STEP ASC
              LIMIT 0, 10
) AS BOARD
JOIN MEMBER
ON MEMBER.MBR_ID = BOARD.BRD_ID
LEFT JOIN (
                    SELECT LIKE_FNO, COUNT(*) AS BRD_LIKECOUNT
                    FROM LIKES
 ) LIKES
ON LIKES.LIKE_FNO = BRD_NO


-- 해당 메뉴 게시글 조회
SELECT BRD_NO, BRD_TYPE, BRD_DIVIDE, BRD_ID, BRD_TITLE, BRD_CONTENT, BRD_GNO, BRD_STEP, BRD_INDENT, BRD_COUNT, BRD_AVAILABLE, BRD_DATE,
                          MEMBER.MBR_PROFILE, MEMBER.MBR_NICK, MEMBER.MBR_ID,
                          COALESCE(BRD_LIKECOUNT,0) AS BRD_LIKECOUNT,
                          COALESCE(BRD_COMMENTCOUNT,0) AS BRD_COMMENTCOUNT
FROM (
              SELECT * FROM BOARD
              WHERE BRD_NO = 3
              AND BRD_TYPE = 'community'
) AS BOARD
JOIN MEMBER
ON MEMBER.MBR_ID = BOARD.BRD_ID
LEFT JOIN (
                    SELECT LIKE_FNO, COUNT(*) AS BRD_LIKECOUNT
                    FROM LIKES WHERE LIKE_FNO = 3
 ) LIKES
ON LIKES.LIKE_FNO = BRD_NO
LEFT JOIN (
                    SELECT CMT_BNO, COUNT(*) AS BRD_COMMENTCOUNT
                    FROM COMMENT WHERE CMT_BNO = 3
 ) COMMENT
ON COMMENT.CMT_BNO = BRD_NO


-- 좋아요 등록 확인 여부
SELECT COUNT(*) FROM LIKES
WHERE LIKE_FNO = 1 AND LIKE_ID = 'test1';

-- 좋아요 등록
INSERT INTO LIKES(LIKE_NO, LIKE_FNO, LIKE_ID, LIKE_DATE)
VALUES(1, 1, 'test1', NOW());


-- 댓글 리스트 조회
SELECT CMT_NO, CMT_BNO, CMT_ID, CMT_CONTENT, CMT_AVAILABLE, CMT_DATE
                      MBR_NICK, MBR_PROFILE
FROM   ( SELECT * FROM COMMENT WHERE CMT_BNO = 1 ORDER BY CMT_NO ASC ) COMMENT
LEFT JOIN MEMBER
ON MEMBER.MBR_ID = CMT_ID

-- 댓글 등록
INSERT INTO COMMENT(CMT_NO, CMT_BNO, CMT_ID, CMT_CONTENT, CMT_AVAILABLE, CMT_DATE)
VALUES(1, 1, 'test1', '안녕하세요ㅎㅎ', 1, NOW())





