-- 게시글 등록
INSERT INTO BOARD( BRD_NO, BRD_TYPE, BRD_DIVIDE, BRD_ID, BRD_TITLE, BRD_CONTENT, BRD_GNO, BRD_STEP, BRD_INDENT, BRD_COUNT, BRD_AVAILABLE, BRD_DATE )
VALUES(1, 'COMMUNITY', 3, 'TEST1', '안녕하세요', 'ㅎㅎㅎㅎㅎ', 1, 0, 0, 0, 1, NOW() );

-- 답글 등록
INSERT INTO BOARD( BRD_NO, BRD_TYPE, BRD_DIVIDE, BRD_ID, BRD_TITLE, BRD_CONTENT, BRD_GNO, BRD_STEP, BRD_INDENT, BRD_COUNT, BRD_AVAILABLE, BRD_DATE )
VALUES( ( SELECT * FROM ( SELECT MAX(BRD_NO)+1 FROM BOARD ) A ),
                'COMMUNITY', 3, 'TEST1', '안녕하세요', 'ㅎㅎㅎㅎㅎ',
                ( SELECT * FROM ( SELECT BRD_GNO FROM BOARD WHERE BRD_NO = 1 ) X ),
                ( SELECT * FROM ( select brd_step+1 from board where brd_no=1002) X ),
                ( SELECT * FROM ( select brd_indent+1 from board where brd_no=1002) X ),
                0, 1, NOW() );

-- 답글로 먼저 등록된 게시글 STEP 증가
UPDATE BOARD SET BRD_STEP = BRD_STEP+1
WHERE
BRD_GNO = ( SELECT * FROM ( SELECT BRD_GNO FROM BOARD WHERE BRD_NO = 1 ) AS A )
AND
BRD_STEP > ( SELECT * FROM ( SELECT BRD_STEP FROM BOARD WHERE BRD_NO = 1 ) AS B );

-- 가장 높은 게시글 번호 조회
 SELECT MAX(BRD_NO) FROM BOARD;

-- 데이터로그 등록
INSERT INTO DATALOG(DLG_NO, DLG_FNO, DLG_TYPE, DLG_ID, DLG_TEXT, DLG_DATE)
VALUES(1, 1, 'community', 'test1', '안녕하세요ㅎㅎㅎ', NOW())

-- 해당 메뉴 리스트 조회
SELECT BRD_NO, BRD_TYPE, BRD_DIVIDE, BRD_ID, BRD_TITLE, BRD_CONTENT, BRD_GNO, BRD_STEP, BRD_INDENT, BRD_COUNT, BRD_AVAILABLE, BRD_DATE,
                          MEMBER.MBR_PROFILE, MEMBER.MBR_NICK
FROM (
              SELECT * FROM BOARD
              WHERE BRD_TYPE = 'community'
              ORDER BY BRD_GNO DESC, BRD_STEP ASC
              LIMIT 0, 10
) AS BOARD
LEFT JOIN MEMBER
ON MEMBER.MBR_ID = BOARD.BRD_ID


-- 해당 메뉴 게시글 조회
SELECT BRD_NO, BRD_TYPE, BRD_DIVIDE, BRD_ID, BRD_TITLE, BRD_CONTENT, BRD_GNO, BRD_STEP, BRD_INDENT, BRD_COUNT, BRD_AVAILABLE, BRD_DATE,
                          MEMBER.MBR_PROFILE, MEMBER.MBR_NICK
FROM (
              SELECT * FROM BOARD
              WHERE BRD_NO = #{brdNo}
              AND BRD_TYPE = #{brdType}
) AS BOARD
LEFT JOIN MEMBER
ON MEMBER.MBR_ID = BOARD.BRD_ID