-- 회원가입 ( MBR_CODE UUID / MBR_PASS Encode value : test )
INSERT INTO MEMBER(MBR_NO, MBR_TYPE, MBR_AUTH, MBR_CODE, MBR_ID, MBR_PASS, MBR_NICK,MBR_EMAIL, MBR_PROFILE, MBR_CONNECT, MBR_JOIN)
VALUES(1, 'none', 'none', 'dbafe1e6-cf08-4752-a3e2-791fbb770ef2', 'test1', '$2a$10$Ggzsao809tjI0CFTtPbDfO/mkd4Mz5MEWmPCOOkeBf3ePxCUpp02u', '테스터1','bytrustu@gmail.com', 'kakao-1.png', NOW(), NOW());

INSERT INTO MEMBER(MBR_NO, MBR_TYPE, MBR_AUTH, MBR_CODE, MBR_ID, MBR_PASS, MBR_NICK,MBR_EMAIL, MBR_PROFILE, MBR_CONNECT, MBR_JOIN)
VALUES(2, 'none', 'none', 'ce53bd4f-9d1f-45be-b57d-1c6b4b139a75', 'test2', '$2a$10$Ggzsao809tjI0CFTtPbDfO/mkd4Mz5MEWmPCOOkeBf3ePxCUpp02u', '테스터2','tiamo198712@gmail.com', 'kakao-2.png', NOW(), NOW());


-- 회원타입값확인
SELECT MBR_TYPE FROM MEMBER WHERE MBR_ID = 'test1';
SELECT MBR_TYPE FROM MEMBER WHERE MBR_ID = 'test2';

-- 회원이메일값확인
SELECT MBR_EMAIL FROM MEMBER WHERE MBR_ID = 'TEST1';
SELECT MBR_EMAIL FROM MEMBER WHERE MBR_ID = 'TEST2';

-- 회원코드값확인
SELECT MBR_CODE FROM MEMBER WHERE MBR_ID = 'TEST1';
SELECT MBR_CODE FROM MEMBER WHERE MBR_ID = 'TEST2';

-- 회원코드값갱신
UPDATE MEMBER SET MBR_CODE = 'dbafe1e6-cf08-4752-a3e2-791fbb770ef2'
WHERE MBR_ID = 'TEST1';

-- 회원인증조회
SELECT COUNT(*) FROM MEMBER
WHERE MBR_ID = 'TEST1' AND MBR_CODE = 'ce53bd4f-9d1f-45be-b57d-1c6b4b139a75';

SELECT COUNT(*) FROM MEMBER
WHERE MBR_ID = 'TEST2' AND MBR_CODE = 'ce53bd4f-9d1f-45be-b57d-1c6b4b139a75';

-- 회원활성화및코드갱신
UPDATE MEMBER
SET MBR_TYPE = 'NORMAL', MBR_AUTH = 'NORMAL', MBR_CODE = 'dbafe1e6-cf08-4752-a3e2-791fbb770ef2', MBR_CONNECT = NOW(), MBR_JOIN = NOW()
WHERE MBR_ID = 'TEST1';

UPDATE MEMBER
SET MBR_TYPE = 'NORMAL', MBR_AUTH = 'NORMAL', MBR_CODE = 'dbafe1e6-cf08-4752-a3e2-791fbb770ef2', MBR_CONNECT = NOW(), MBR_JOIN = NOW()
WHERE MBR_ID = 'TEST2';

-- 아이디 중복 조회
SELECT COUNT(*) FROM MEMBER WHERE MBR_ID = 'TEST1';
SELECT COUNT(*) FROM MEMBER WHERE MBR_ID = 'TEST2';

-- 아이디 상태타입 조회
SELECT MBR_TYPE FROM MEMBER WHERE MBR_ID = 'TEST1';
SELECT MBR_TYPE FROM MEMBER WHERE MBR_ID = 'TEST2';

-- 이메일 중복 조회
SELECT COUNT(*) FROM MEMBER WHERE MBR_EMAIL =  'TEST1';
SELECT COUNT(*) FROM MEMBER WHERE MBR_EMAIL =  'TEST2';