-- 회원가입 ( MBR_CODE UUID / MBR_PASS Encode value : test )
INSERT INTO MEMBER(MBR_NO, MBR_TYPE, MBR_AUTH, MBR_CODE, MBR_ID, MBR_PASS, MBR_NICK,MBR_EMAIL, MBR_PROFILE, MBR_CONNECT, MBR_JOIN)
VALUES(1, 'none', 'none', 'dbafe1e6-cf08-4752-a3e2-791fbb770ef2', 'test1', '$2a$10$Ggzsao809tjI0CFTtPbDfO/mkd4Mz5MEWmPCOOkeBf3ePxCUpp02u', '테스터1','bytrustu@gmail.com', 'kakao-1.png', NOW(), NOW());

INSERT INTO MEMBER(MBR_NO, MBR_TYPE, MBR_AUTH, MBR_CODE, MBR_ID, MBR_PASS, MBR_NICK,MBR_EMAIL, MBR_PROFILE, MBR_CONNECT, MBR_JOIN)
VALUES(2, 'none', 'none', 'ce53bd4f-9d1f-45be-b57d-1c6b4b139a75', 'test2', '$2a$10$Ggzsao809tjI0CFTtPbDfO/mkd4Mz5MEWmPCOOkeBf3ePxCUpp02u', '테스터2','tiamo198712@gmail.com', 'kakao-2.png', NOW(), NOW());


-- 회원타입값확인
SELECT MBR_TYPE FROM MEMBER WHERE MBR_ID = 'test1';
SELECT MBR_TYPE FROM MEMBER WHERE MBR_ID = 'test2';

-- 회원이메일값확인
SELECT MBR_EMAIL FROM MEMBER WHERE MBR_ID = 'TEST1';
SELECT MBR_EMAIL FROM MEMBER WHERE MBR_ID = 'TEST2';

-- 회원코드값확인
SELECT MBR_CODE FROM MEMBER WHERE MBR_ID = 'TEST1';
SELECT MBR_CODE FROM MEMBER WHERE MBR_ID = 'TEST2';

-- 회원코드값갱신
UPDATE MEMBER SET MBR_CODE = 'dbafe1e6-cf08-4752-a3e2-791fbb770ef2'
WHERE MBR_ID = 'TEST1';

-- 회원인증조회
SELECT COUNT(*) FROM MEMBER
WHERE MBR_ID = 'TEST1' AND MBR_CODE = 'ce53bd4f-9d1f-45be-b57d-1c6b4b139a75';

SELECT COUNT(*) FROM MEMBER
WHERE MBR_ID = 'TEST2' AND MBR_CODE = 'ce53bd4f-9d1f-45be-b57d-1c6b4b139a75';

-- 회원활성화및코드갱신
UPDATE MEMBER
SET MBR_TYPE = 'NORMAL', MBR_AUTH = 'NORMAL', MBR_CODE = 'dbafe1e6-cf08-4752-a3e2-791fbb770ef2', MBR_CONNECT = NOW(), MBR_JOIN = NOW()
WHERE MBR_ID = 'TEST1';

UPDATE MEMBER
SET MBR_TYPE = 'NORMAL', MBR_AUTH = 'NORMAL', MBR_CODE = 'dbafe1e6-cf08-4752-a3e2-791fbb770ef2', MBR_CONNECT = NOW(), MBR_JOIN = NOW()
WHERE MBR_ID = 'TEST2';

-- 아이디 중복 조회
SELECT COUNT(*) FROM MEMBER WHERE MBR_ID = 'TEST1';
SELECT COUNT(*) FROM MEMBER WHERE MBR_ID = 'TEST2';

-- 아이디 상태타입 조회
SELECT MBR_TYPE FROM MEMBER WHERE MBR_ID = 'TEST1';
SELECT MBR_TYPE FROM MEMBER WHERE MBR_ID = 'TEST2';

-- 이메일 중복 조회
SELECT COUNT(*) FROM MEMBER WHERE MBR_EMAIL =  'TEST1';
SELECT COUNT(*) FROM MEMBER WHERE MBR_EMAIL =  'TEST2';

-- 닉네임 중복 조회
SELECT COUNT(*) FROM MEMBER WHERE MBR_NICK = 'TEST1';
SELECT COUNT(*) FROM MEMBER WHERE MBR_NICK = 'TEST2';

-- 회원 접속 통계 조회
SELECT COALESCE(COUNT(*),0) AS COUNT FROM VISIT WHERE VIS_ID = 'TEST1';
SELECT COALESCE(COUNT(*),0) AS COUNT FROM VISIT WHERE VIS_ID = 'TEST2';

-- 회원 정보 조회
SELECT MBR_NO, MBR_TYPE, MBR_AUTH, MBR_CODE, MBR_ID, MBR_PASS, MBR_NICK,MBR_EMAIL, MBR_PROFILE, MBR_CONNECT, MBR_JOIN FROM MEMBER
WHERE MBR_ID = 'TEST1';

SELECT MBR_NO, MBR_TYPE, MBR_AUTH, MBR_CODE, MBR_ID, MBR_PASS, MBR_NICK,MBR_EMAIL, MBR_PROFILE, MBR_CONNECT, MBR_JOIN FROM MEMBER
WHERE MBR_ID = 'TEST2';

-- 승인나지않은 이메일로 아이디 조회
SELECT MBR_ID FROM MEMBER WHERE MBR_EMAIL = 'A2F@F2.CM' AND MBR_TYPE = 'NONE';
SELECT MBR_ID FROM MEMBER WHERE MBR_EMAIL = 'BYTRUSTU@GMAIL.COM' AND MBR_TYPE = 'NONE';

-- 승인나지않은 이메일 변경
UPDATE MEMBER SET MBR_EMAIL = 'BYTRUSTU@GMAIL.COM' WHERE MBR_EMAIL = 'BYTRUSTU@GMAIL.COM' AND MBR_TYPE = 'NONE';
UPDATE MEMBER SET MBR_EMAIL = 'TIAMO198712@NAVER.COM' WHERE MBR_EMAIL = 'BYTRUSTU@GMAIL.COM' AND MBR_TYPE = 'NONE';

-- 승인나지않은 회원정보 삭제
DELETE FROM MEMBER WHERE MBR_ID = 'TEST1' AND MBR_TYPE = 'NONE';
DELETE FROM MEMBER WHERE MBR_ID = 'TEST2' AND MBR_TYPE = 'NONE';

-- 회원 이메일 정보 확인
SELECT COUNT(*) FROM MEMBER WHERE MBR_EMAIL = 'tiamo198712@naver.com' AND ( MBR_AUTH = 'NORMAL' OR MBR_AUTH = 'ADMIN' );
SELECT COUNT(*) FROM MEMBER WHERE MBR_EMAIL = 'bytrustu@gmail.com' AND ( MBR_AUTH = 'NORMAL' OR MBR_AUTH = 'ADMIN' );

-- 회원 이메일 인증을 통한 패스워드 변경
UPDATE MEMBER SET MBR_PASS = 'dbafe1e6-cf08-4752-a3e2-791fbb770ef2' WHERE MBR_ID = 'TEST1';
UPDATE MEMBER SET MBR_PASS = 'dbafe1e6-cf08-4752-a3e2-791fbb770ef2' WHERE MBR_ID = 'TEST2';

-- 회원 소셜 로그인 가입 여부 조회
SELECT COUNT(*) FROM MEMBER WHERE MBR_ID = "01242019460" AND MBR_TYPE = "GOOGLE";
SELECT COUNT(*) FROM MEMBER WHERE MBR_ID = "239659123568239" AND MBR_TYPE = "FACEBOOK";
SELECT COUNT(*) FROM MEMBER WHERE MBR_ID = "1928561298" AND MBR_TYPE = "NAVER";
SELECT COUNT(*) FROM MEMBER WHERE MBR_ID = "210567210" AND MBR_TYPE = "KAKAO";

-- 회원 소셜 정보 조회
SELECT MBR_TYPE, MBR_AUTH, MBR_ID, MBR_NICK, MBR_PROFILE, MBR_CONNECT, MBR_JOIN FROM MEMBER WHERE MBR_ID = "01242019460" AND MBR_TYPE = "GOOGLE";
SELECT MBR_TYPE, MBR_AUTH, MBR_ID, MBR_NICK, MBR_PROFILE, MBR_CONNECT, MBR_JOIN FROM MEMBER WHERE MBR_ID = "239659123568239" AND MBR_TYPE = "FACEBOOK";
SELECT MBR_TYPE, MBR_AUTH, MBR_ID, MBR_NICK, MBR_PROFILE, MBR_CONNECT, MBR_JOIN FROM MEMBER WHERE MBR_ID = "1928561298" AND MBR_TYPE = "NAVER";
SELECT MBR_TYPE, MBR_AUTH, MBR_ID, MBR_NICK, MBR_PROFILE, MBR_CONNECT, MBR_JOIN FROM MEMBER WHERE MBR_ID = "210567210" AND MBR_TYPE = "KAKAO";

-- 회원 소셜 가입
INSERT INTO MEMBER(MBR_NO, MBR_TYPE, MBR_AUTH, MBR_CODE, MBR_ID, MBR_PASS, MBR_NICK,MBR_EMAIL, MBR_PROFILE, MBR_CONNECT, MBR_JOIN)
VALUES(1, 'GOOGLE', 'NORMAL', 'dbafe1e6-cf08-4752-a3e2-791fbb770ef2', '01242019460', '$2a$10$Ggzsao809tjI0CFTtPbDfO/mkd4Mz5MEWmPCOOkeBf3ePxCUpp02u', '하하','01242019460@gmail.com', 'siba-default.png', NOW(), NOW());

INSERT INTO MEMBER(MBR_NO, MBR_TYPE, MBR_AUTH, MBR_CODE, MBR_ID, MBR_PASS, MBR_NICK,MBR_EMAIL, MBR_PROFILE, MBR_CONNECT, MBR_JOIN)
VALUES(2, 'FACEBOOK', 'NORMAL', 'ce53bd4f-9d1f-45be-b57d-1c6b4b139a75', '239659123568239', '$2a$10$Ggzsao809tjI0CFTtPbDfO/mkd4Mz5MEWmPCOOkeBf3ePxCUpp02u', '호호','239659123568239@gmail.com', 'siba-default.png', NOW(), NOW());

-- 포인트 생성
INSERT INTO POINT(PNT_NO, PNT_ID, PNT_SCORE) VALUES(1, 'TEST1', 100);
INSERT INTO POINT(PNT_NO, PNT_ID, PNT_SCORE) VALUES(1, 'TEST2', 100);

-- 포인트 증가/감소
UPDATE POINT SET PNT_SCORE = PNT_SCORE+-100  WHERE PNT_ID = 'TEST1';
UPDATE POINT SET PNT_SCORE = PNT_SCORE+200  WHERE PNT_ID = 'TEST1';

-- 포인트 수정
UPDATE POINT SET PNT_SCORE = 200  WHERE PNT_ID = 'TEST1';
UPDATE POINT SET PNT_SCORE = 1000  WHERE PNT_ID = 'TEST1';

-- 오늘 접속한 유저인지 확인조회
SELECT COUNT(*) FROM MEMBER WHERE MBR_ID = 'TEST1' AND DATE_FORMAT(MBR_CONNECT, '%Y-%m-%d') = CURDATE();
SELECT COUNT(*) FROM MEMBER WHERE MBR_ID = 'TEST2' AND DATE_FORMAT(MBR_CONNECT, '%Y-%m-%d') = CURDATE();

-- 접속시간갱신
UPDATE MEMBER SET MBR_CONNECT = NOW() WHERE MBR_ID='TEST1';
UPDATE MEMBER SET MBR_CONNECT = NOW() WHERE MBR_ID='TEST2';

-- 방문자정보등록
INSERT INTO VISIT(VIS_NO, VIS_ID, VIS_DATE) VALUES(1,'TEST1',NOW());
INSERT INTO VISIT(VIS_NO, VIS_ID, VIS_DATE) VALUES(2,'TEST2',NOW());